sudo: false
language: python
install: 
        - pip3 install tox-travis
script: 
        - tox
addons:
        apt:
                packages:
                        - fakeroot
                        - debhelper
                        - python3-setuptools
matrix:
        include:
                - os: "linux"
                  dist: "xenial"
                  python: "3.5"
                  env: "TOXENV=flake8"
                - os: "linux"
                  dist: "xenial"
                  python: "3.5"
                - os: "linux"
                  dist: "xenial"
                  python: "3.6"
                - os: "linux"
                  dist: "xenial"
                  python: "3.7"
                - os: "windows"
                  filter_secrets: false
                  language: shell
                  python: "3.7"
                  env: 
                        - "PATH=/c/python37:/c/python37/Scripts:$PATH"
                        - "TOXENV=py37-win"
                  before_install:
                        - choco install python make
                        - cp /c/python37/python.exe /c/python37/python3.exe
deploy:
        on:
                all_branches: true
        skip_cleanup: true
        local_dir: build/

        provider: s3
        access_key_id: $ARTIFACTS_KEY
        secret_access_key: $ARTIFACTS_SECRET
        bucket: $ARTIFACTS_BUCKET
        upload-dir: $TRAVIS_REPO_SLUG/$TRAVIS_JOB_NUMBER
