sudo: false
language: python
install: 
        - pip3 install -r requirements.txt -r requirements-extra.txt
script: tox
matrix:
        include:
                - os: "linux"
                  dist: "xenial"
                  python: "3.5"
                - os: "linux"
                  dist: "xenial"
                  python: "3.6"
                - os: "linux"
                  dist: "xenial"
                  python: "3.7"
                - os: "windows"
                  language: shell
                  python: "3.8"
                  env: "PATH=/c/python38:/c/python38/Scripts:$PATH"
                  before_install:
                          - choco install python make
                          - cp /c/python38/python.exe /c/python38/python3.exe
                  before_script:
                          - pip3 install -r requirements-windows.txt
                          - python3 build.py
                  script:
                          - tox -e WINDOWS
deploy:
        provider: s3
        access_key_id: "$ARTIFACTS_KEY"
        secret_access_key: "$ARTIFACTS_SECRET"
        bucket: "jpvlsmv.artifacts"
        skip_cleanup: true
        upload-dir: "$TRAVIS_REPO_SLUG/$TRAVIS_JOB_NUMBER"
        on:
              repo: jpvlsmv/dupeguru
              all_branches: true
