sudo: false
language: python
install: 
        - pip3 install tox
script: 
        - tox
matrix:
        include:
                - os: "linux"
                  dist: "xenial"
                  python: "3.5"
                  env: "TOXENV=flake8"
                - os: "linux"
                  dist: "xenial"
                  python: "3.5"
                - os: "linux"
                  dist: "xenial"
                  python: "3.6"
                - os: "linux"
                  dist: "xenial"
                  python: "3.7"
                - os: "windows"
                  filter_secrets: false
                  language: shell
                  python: "3.7"
                  env: 
                        - "PATH=/c/python37:/c/python37/Scripts:$PATH"
                        - "TOXENV=py37-win"
                  before_install:
                        - choco install python make
                        - cp /c/python37/python.exe /c/python37/python3.exe
addons:
        artifacts:
                paths:
                        - build/
